name: ci

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/ci.yml

jobs:

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install -e .[tests]

    - run: mypy
    - run: pytest
